- hosts: test #servers
  vars:
    mysql_root_password: root
    http_port: 80
    domain: "{{ inventory_hostname }}"

  tasks:
  - name: Packages
    apt: pkg={{item}} state=present update_cache=yes
    with_items:
    # - libmysqlclient-dev
    # - apache2
    # - mysql-server
    # - php5 
    # - libapache2-mod-php5
    # - php5-mcrypt 
    # - php5-mysql
    #
    # ^ probably installed by tasksel
    
    - python-mysqldb
    - unzip
    - curl
    - wget
    - libapache2-mod-php5
    - php5-gd
    # - gtar no such package (following task is a workaround)

  - name: create symlink for gtar (required by ansible unarchive module)
    file:
      src: /bin/tar
      dest: /bin/gtar        
      state: link

  - name: ensure mysql is running and starts on boot
    service: name=mysql state=started enabled=true

  - name: MySQL | Configuration file, my.cnf
    action: template src=templates/my.cnf dest=/etc/mysql/my.cnf
    tags: common
    notify:
      - restart mysql
 
  - name: Creates directory
    file: path=/var/www/egea state=directory

  - name: copy egea
    unarchive:
      src: http://blogengine.ru/download/e2_distr_v2970.zip
      dest: /var/www/egea/
      owner: www-data
      group: www-data
      creates: /var/www/egea/favicon.ico
      exclude: readme.txt
      remote_src: True

  - name: create egea config
    template: src=templates/config.php dest=/var/www/egea/user/config.php

  - name: download info.php
    copy:
      src: dist/info.php
      dest: /var/www/egea/info.php

  # Setting up apache to play nice with new website

  - name: create virtual host file
    template: src=templates/virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

  - name: apache2.conf
    template: src=templates/apache2.conf dest=/etc/apache2/apache2.conf
    notify:
      - restart apache2

  - name: ports
    template: src=templates/ports.conf dest=/etc/apache2/ports.conf
    notify:
      - restart apache2

  - name: enabled mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
      - restart apache2

  - name: apache2 listen on port {{ http_port }}
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
    notify:
      - restart apache2

  - name: a2ensite {{ domain }}
    command: a2ensite {{ domain }}
    args:
      creates: /etc/apache2/sites-enabled/{{ domain }}.conf
    notify:
      - restart apache2

  - name: a2dissite 000-default
    command: a2dissite 000-default
    args:
      creates: /etc/apache2/sites-disabled/000-default.conf
    notify:
      - restart apache2

  - name: Create a new database with name 'e2'
    mysql_db:
      name: e2
      login_user: root
      login_password: "{{ mysql_root_password }}"
      state: present

  - name: Set user and group
    file:
      path: /var/www
      owner: www-data
      group: www-data
      recurse: Yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart mysql
      service: name=mysql state=restarted

